### ISSUE TITLE
Index-based upsampling?

### ISSUE THREAD

**Issue by tivanovska** [imlab-uiip/keras-segnet#2]
Hi,
as far as i understand, this implementation does not use the index-based upsampling, but uses the Upsample2D Keras layer. Do you have any ideas on how to implement the index passing and how much of the impact this should have? 

Thanks!
Kind regards,
Tanja

**Comment by eclique** [comment]
Hi @tivanovska,
yes, this implementation doesn't use index-based upsampling, and I probably shouldn't have called it SegNet for that matter.
I have added files with the layers supporting index transferring (for theano backend only). But unfortunately, it won't work with the current version of theano. It has been implemented in 0.8.2. I wasn't able to adapt it in reasonable time.
In order to transfer indices, you need to solve three problems:
1. Compute indices during max pooling. I did it by implementing custom operations based on theano pooling. They calculate the mask of `{0, 1}` for non-max/max.
2. Pass indices from MaxPooling to UpSampling layers. I did it by storing the mask in the MP layer and then reading it from US layer.
3. Arrange maxima according to indices during US. It could be done by creating another backend operation, but I used `switch` to pick values from either zeros or resized image depending on the mask.

For my task index transferring didn't give significant increase in segmentation quality compared to simple deconvolutional network presented in this repository.

Best regards,
Vitali.

**Comment by tivanovska** [comment]
Thanks!
